server:
  port: 6363

spring:
  application.name: throttledendpoints

bucket4j:
  enabled: true
  filters:
    - cache-name: rate-limit-buckets
      hide-http-response-headers: true
      url: .*
      rate-limits:
        - cache-key: "getRemoteAddr()"
          bandwidths:
          - capacity: 5
            time: 10
            unit: seconds
